import type { Task } from "../../types/task";

export const mockTasks: Task[] = [
  {
    id: "task-01",
    title: "영어 단어 20개 학습",
    date: "2026-06-02",
    dueDate: null,
    time: "09:00",
    source: "routine",
    status: "planned",
    priority: "high",
    todaySortGroup: "timed_today",
    taskKindOption: "repeat",
    postponeCount: 0,
    progressPercent: 0,
    remainingPercent: 100,
    reminderAt: "2026-06-02T09:00:00+09:00",
    parentTaskId: null,
    isFixed: true,
    calendarColor: "#FFE680",
    repeatKind: "daily",
    repeatDaysOfWeek: [],
    repeatDayOfMonth: null,
    memo: "20개 학습 후 질문으로 넘어가기"
  },
  {
    id: "task-02",
    title: "이력서 문장 다듬기",
    date: "2026-06-02",
    dueDate: null,
    time: null,
    source: "manual",
    status: "planned",
    priority: "normal",
    todaySortGroup: "pulled_to_today",
    taskKindOption: "today",
    postponeCount: 0,
    progressPercent: 30,
    remainingPercent: 70,
    reminderAt: null,
    parentTaskId: "task-origin-02",
    memo: "오늘로 가져온 작업"
  },
  {
    id: "task-03",
    title: "월수금 운동",
    date: "2026-06-02",
    dueDate: null,
    periodStartDate: "2026-05-01",
    periodEndDate: "2026-06-30",
    time: null,
    source: "routine",
    status: "planned",
    priority: "normal",
    todaySortGroup: "repeat_today",
    taskKindOption: "repeat",
    postponeCount: 1,
    progressPercent: 0,
    remainingPercent: 100,
    reminderAt: "2026-06-02T19:10:00+09:00",
    parentTaskId: null,
    calendarColor: "#BFE3FF",
    repeatKind: "weekly",
    repeatDaysOfWeek: [1, 3, 5],
    repeatDayOfMonth: null,
    memo: "사용자가 직접 설정한 요일 반복"
  },
  {
    id: "task-04",
    title: "공과금 납부",
    date: null,
    dueDate: "2026-06-06",
    time: null,
    source: "deadline",
    status: "planned",
    priority: "high",
    todaySortGroup: "near_deadline",
    taskKindOption: "dday",
    postponeCount: 0,
    progressPercent: 0,
    remainingPercent: 100,
    reminderAt: null,
    parentTaskId: null,
    calendarColor: "#FF9F8F",
    memo: "마감 D-4"
  },
  {
    id: "task-05",
    title: "포트폴리오 보기",
    date: "2026-06-02",
    dueDate: null,
    time: null,
    source: "manual",
    status: "started",
    priority: "normal",
    todaySortGroup: "started",
    taskKindOption: "today",
    postponeCount: 0,
    progressPercent: 0,
    remainingPercent: 100,
    reminderAt: null,
    parentTaskId: null,
    memo: "진행 중"
  },
  {
    id: "task-06",
    title: "읽고 싶은 책 목록 정리",
    date: null,
    dueDate: null,
    time: null,
    source: "no_date",
    status: "planned",
    priority: "low",
    todaySortGroup: "no_date",
    taskKindOption: "no_deadline",
    postponeCount: 0,
    progressPercent: 0,
    remainingPercent: 100,
    reminderAt: null,
    parentTaskId: null,
    calendarColor: "#E8E1D2",
    memo: "날짜 없는 할 일"
  }
];
